Repository openshift/ocp-release-operator-sdk, pull requests merged in 2019-03, with the labels that each got.

#4 add ansible logging aggregator
  Dockerfile
  bin/ao-logs
Labels: lgtm, size/S

#5 Revert "add ansible logging aggregator"
  Dockerfile
  bin/ao-logs
Labels: size/S

#6 remove proxy test because it needs a cluster.
  hack/tests/unit.sh
  pkg/ansible/proxy/proxy_test.go
Labels: size/XS
