Repository openshift/ocp-release-operator-sdk, pull requests merged in 2020-03, with the labels that each got.

#48 add helm image release files
  Makefile
  release/helm/Dockerfile
  release/helm/bin/entrypoint
  release/helm/bin/user_setup
  release/helm/upstream.Dockerfile
Labels: approved, lgtm, size/M

#51 fix build and ci ocp for helm image
  ci/dockerfiles/ansible-e2e.Dockerfile
  ci/tests/e2e-ansible.sh
  ci/tests/e2e-helm.sh
  release/helm/Dockerfile
Labels: approved, lgtm, size/S

#52 fix /ci/tests/e2e-helm.sh
  ci/dockerfiles/helm-e2e-hybrid.Dockerfile
  ci/dockerfiles/helm-e2e.Dockerfile
Labels: approved, lgtm

#53 small improvements fixes in the helm scripts used by the ci
  ci/tests/e2e-helm.sh
  ci/tests/scaffolding/e2e-helm-scaffold-hybrid.sh
  ci/tests/scaffolding/e2e-helm-scaffold.sh
Labels: approved, lgtm

#54 internal/scaffold/helm/entrypoint.go: resolve merge issue
  internal/scaffold/helm/entrypoint.go
  release/helm/bin/entrypoint
Labels: approved, lgtm

#40 Bug 1793308: internal/scaffold: don't change /etc/passwd perms [release-4.2]
  CHANGELOG.md
  bin/entrypoint
  bin/user_setup
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
  go.mod
  images/scorecard-proxy/bin/entrypoint
  images/scorecard-proxy/bin/user_setup
  internal/pkg/scaffold/ansible/entrypoint.go
  internal/pkg/scaffold/ansible/usersetup.go
  internal/pkg/scaffold/entrypoint.go
  internal/pkg/scaffold/entrypoint_test.go
  internal/pkg/scaffold/helm/entrypoint.go
  internal/pkg/scaffold/helm/usersetup.go
  internal/pkg/scaffold/usersetup.go
  internal/pkg/scaffold/usersetup_test.go
  test/test-framework/build/bin/entrypoint
  test/test-framework/build/bin/user_setup
Labels: bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L
