Repository openshift/ocp-release-operator-sdk, pull requests merged in 2020-02, with the labels that each got.

#42 Bug 1793310: internal/scaffold: don't change /etc/passwd perms [release-4.4]
  CHANGELOG.md
  bin/entrypoint
  bin/user_setup
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
  images/scorecard-proxy/bin/entrypoint
  images/scorecard-proxy/bin/user_setup
  internal/scaffold/ansible/entrypoint.go
  internal/scaffold/ansible/usersetup.go
  internal/scaffold/entrypoint.go
  internal/scaffold/entrypoint_test.go
  internal/scaffold/helm/entrypoint.go
  internal/scaffold/helm/usersetup.go
  internal/scaffold/usersetup.go
  internal/scaffold/usersetup_test.go
  test/test-framework/build/bin/entrypoint
  test/test-framework/build/bin/user_setup
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#41 Bug 1793309: internal/scaffold: don't change /etc/passwd perms [release-4.3]
  CHANGELOG.md
  bin/entrypoint
  bin/user_setup
  ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
  ci/dockerfiles/ansible.Dockerfile
  images/scorecard-proxy/bin/entrypoint
  images/scorecard-proxy/bin/user_setup
  internal/scaffold/ansible/entrypoint.go
  internal/scaffold/ansible/usersetup.go
  internal/scaffold/entrypoint.go
  internal/scaffold/entrypoint_test.go
  internal/scaffold/helm/entrypoint.go
  internal/scaffold/helm/usersetup.go
  internal/scaffold/usersetup.go
  internal/scaffold/usersetup_test.go
  test/test-framework/build/bin/entrypoint
  test/test-framework/build/bin/user_setup
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#44 Bug 1808102: Pin requests library to compatible version
  Dockerfile
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
